import type { StageTemplate } from '../../base.js';

export const gitPr: StageTemplate = {
  name: 'git-pr',
  type: 'command',
  description: 'Create a pull request on GitHub using gh CLI.',
  prompt: '',
  command:
    "cd /workspace/project && TITLE=$(git log -1 --pretty=%s) && BODY=$(git log -1 --pretty=%b) && gh pr create --title \"$TITLE\" --body \"${BODY:-Auto-generated by AerArt}\" && echo '[STAGE_COMPLETE]'",
  image: 'alpine/git',
  mounts: {
    project: 'ro',
  },
  requiredEnv: ['GITHUB_TOKEN'],
  transitions: [
    { marker: '[STAGE_COMPLETE]', next: null },
    { marker: '[STAGE_ERROR]', next: null, prompt: 'PR creation failed — check GITHUB_TOKEN' },
  ],
};
